apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
        - name: logging
          image: sadik789diwan/logging:latest   # base image
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30